Sprint 2 behaviour
dranikpg/bsu-game pull request #10
Opened 2021-04-06 12:10 UTC by NB6361

Now we can create behaviors for different entities. Created first level

2021-04-06 13:27 UTC, maxim12321 requested changes
Во-первых, много магических чисел в коде уровня. Возможно, надо вынести это в какие-нибудь константы, или что-то еще придумать.

Во-вторых, код создания игрока и охранника внутри уровня надо будет вынести куда-то в другое место, сделать функции ```CreatePlayer()``` и ```CreateGuard()```, так как это все равно будет повторяться от уровня к уровню. Но видимо это уже позже.

2021-04-06 13:27 UTC, maxim12321 commented on CMakeLists.txt
> +        src/resources/behaviour.h
Хедер файл тут точно лишний

2021-04-06 13:27 UTC, maxim12321 commented on assets/resources.qrc
> +</RCC>
А тут не хватает пустой строчки в конце файла

2021-04-06 13:27 UTC, maxim12321 commented on src/components/behaviour_component.h
> +class BehaviourComponent : public ecs::Component {
Кажется компоненты должны быть структурами, а не классами. Тогда и блок public не нужен

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.h
> +}  // namespace level
Почему класс GuardBehaviour находится вместе с BsuEntranceLevel? Можно же было в отдельный файл его вынести

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.h
> +  QPoint main_position_;
Давайте раз уж ```main_position_```, то и ```door_position_```

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.h
> + private:
Пустая строчка перед private:

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +                         (player_pos.position.y() - door_pos_.y())));
Есть функция ```std::hypot(x, y)```, которая вычисляет сумму квадратов x и y

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +  } else {
```
if (distance_to_door <= 180) {
  if (IsCloseToDoor(guard_pos.position)) {
    impulse.shift.setX(0);
  } else {
    impulse.shift.setX(-8);
  }
}
```

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +    impulse.shift.setX(8);
```
if (guard_pos.position == main_position_) {
  impulse.shift.setX(0);
} else {
  impulse.shift.setX(8);
}
```

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +  return (guard_pos.x() - door_pos_.x()) * (guard_pos.x() - door_pos_.x()) < 100;
А просто ```std::abs(guard_pos.x() - door_pos_.x()) < 10``` чем не угодило?)

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +      door_pos_.setY(object.position.y() + object.size.height() / 2);
Кажется много где используются именно координаты середины объекта. Может тогда имеет смысл либо хранить position именно как координаты центра, то есть прибавить половину длины на этапе создания MapObject. Либо же можно сделать какой-то метод, например ```Center()```, который будет возвращать QPoint координаты центра.

2021-04-06 13:27 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +      std::make_shared<GuardBehaviour>(player_, guard_pos.position, door_pos_);
Когда делается ```std::make_shared```, в правой части и так видно, какой тип будет у переменной. Можно написать ```auto guard_behaviour = ...```, тогда кстати и в одну строчку влезет, и вообще красиво

2021-04-06 13:27 UTC, maxim12321 commented on src/map/map_loader.cpp
> +  int y = static_cast<int>(obj.value("y").toDouble() + 1);
Округлять вверх можно через ```std::ceil```

2021-04-06 16:37 UTC, dranikpg commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +  } else {
Наверное стоит вынести -8 в константу `kGuardSpeed`

2021-04-07 17:14 UTC, maxim12321 approved these changes

2021-04-07 17:15 UTC, dranikpg approved these changes

2021-04-07 17:21 UTC, merged