Sprint 3
dranikpg/bsu-game pull request #12
Opened 2021-04-22 20:50 UTC by dranikpg

Переключение уровней, мини-игры

2021-04-23 18:09 UTC, SubaruFallout requested changes

2021-04-23 18:09 UTC, SubaruFallout commented on assets/BSU_entrance.json
>  }
Нету пустой строки в конце

2021-04-23 18:09 UTC, SubaruFallout commented on assets/guard_dialog.json
> +}
Здесь тоже нет пустой строки в конце

2021-04-23 18:09 UTC, SubaruFallout commented on src/components/camera_component.h
> +  float scale;
Их можно разделить пустой строкой

2021-04-23 18:09 UTC, SubaruFallout commented on src/components/path_follow_component.cpp
> +
Вот это прикол. А на самом деле, зачем было добавлять просто пустую строку?

2021-04-23 18:09 UTC, SubaruFallout commented on src/components/dialog_component.h
> +                  utils::PixRect rect);
Здесь нужно передать по ссылке

2021-04-23 18:09 UTC, SubaruFallout commented on src/context/dialog_context.h
> + private:
Я нашел применение той самой пустой строчки.

2021-04-23 18:09 UTC, SubaruFallout commented on src/context/mini_game_context.h
> + private:
Разделяющей пустой строки нету

2021-04-23 18:09 UTC, SubaruFallout commented on src/levels/bsu_entrance/guard_behaviour.h
> +                 std::shared_ptr<resource::Path>  guard_path,
Тут два пробела, нужен один

2021-04-23 18:09 UTC, SubaruFallout commented on src/levels/bsu_entrance/guard_mini_game.h
> +   private:
Нету пустой строчки

2021-04-23 18:09 UTC, SubaruFallout commented on src/levels/bsu_entrance/guard_mini_game.h
> + private:
И здесь нету пустой строчки

2021-04-23 18:09 UTC, SubaruFallout commented on src/resources/dialog.h
> + private:
Empty line please

2021-04-23 18:09 UTC, SubaruFallout commented on src/systems/dialog_system.h
> + private:
Empty line

2021-04-23 18:09 UTC, SubaruFallout commented on src/systems/dialog_system.h
> + private:
Empty line

2021-04-23 18:09 UTC, SubaruFallout commented on src/resources/path.h
> +  explicit Path(QPointF start, QPointF target);
Explicit здесь не нужно

2021-04-23 22:10 UTC, maxim12321 requested changes

2021-04-23 22:10 UTC, maxim12321 commented on src/systems/rendering_system.cpp
> +            + 1 / scale * window_context_->GetSize().height() / 2);
Давайте хотя бы так тогда
```
painter.translate(-camera_pos.position);
painter.translate(window_context_->GetSize().width() / scale / 2,
                  window_context_->GetSize().height() / scale / 2);
```

2021-04-23 22:10 UTC, maxim12321 commented on src/systems/rendering_system.cpp
> +              });
Может попробовать компаратор вынести, например? Хотя бы просто в функцию тут же. Ну а то совсем страшно выглядит, читать сложновато.

2021-04-23 22:10 UTC, maxim12321 commented on src/systems/path_follow_system.cpp
> +  const float precision = 4;
Давайте такую константу вынесем в хедер-файл.

2021-04-23 22:10 UTC, maxim12321 commented on src/resources/dialog.h
> +  std::map<QString, QString> options_;
Раз уж есть using выше, то тогда ```OptionBag options_```

2021-04-23 22:10 UTC, maxim12321 commented on src/resources/dialog.h
> +  std::map<QString, QString> options_;
Тут еще несколько раз такое в файле, и в cpp тоже

2021-04-23 22:10 UTC, maxim12321 commented on src/utils/pix_rect.h
> +struct PixRect {
Может хотя бы ```PixmapRect``` назвать, или еще как-то, но не надо такие сокращения делать

2021-04-23 22:10 UTC, maxim12321 commented on src/utils/pix_rect.cpp
> +//
Commented by maxim12321 on 23.04.21.

2021-04-23 22:10 UTC, maxim12321 commented on src/components/dialog_component.cpp
> +DialogComponent::DialogComponent(const std::shared_ptr<resource::Dialog>& dialog,
Тут, и в следующем конструкторе, можно передавать диалог по значению и делать std::move, как считаете?

2021-04-23 22:10 UTC, maxim12321 commented on src/systems/dialog_system.cpp
> +      dialog->finish_handler(chosen);
```dialog->finish_handler(std::nullopt);```

2021-04-23 22:10 UTC, maxim12321 commented on src/systems/dialog_system.cpp
> +  }
Давайте либо кидать ошибку в таких случаях, либо просто не писать блок else

2021-04-23 22:10 UTC, maxim12321 commented on src/systems/dialog_system.cpp
> +  bool fresh_dialog = false;
Лучше ```is_dialog_fresh```, например, и можно подвинуть эту переменную вниз, к тому месту, где она действительно нужна.

2021-04-23 22:10 UTC, maxim12321 commented on src/resources/level.cpp
> +          background.height() / 2))
Там же есть отличный конструктор от двух параметров, чтобы делать вот так
```
world->CreateEntity()
    .AddComponent<game::PositionComponent>(background.width() / 2,
                                           background.height() / 2)
```

2021-04-23 22:10 UTC, maxim12321 commented on src/resources/level.cpp
> +  point *= 1.0 / camera.scale;
Почему не ```point /= camera.scale```?)

2021-04-23 22:10 UTC, maxim12321 commented on src/resources/level.cpp
> +  point.ry() += window_size.height() / 2;
Есть вариант сделать вот так
```point += QPointF(window_size.width(), window_size.height()) / 2;```
Или вообще это сразу в return'е прибавить, но мб тогда уже каша получается

2021-04-23 22:10 UTC, maxim12321 commented on src/levels/bsu_entrance/guard_mini_game.cpp
> +game::GuardMiniGame::GuardMiniGame(const game::GuardMiniGame::Callback& callback,
Опять же, можно по значению и через std::move

2021-04-23 22:10 UTC, maxim12321 commented on src/levels/bsu_entrance/guard_behaviour.cpp
> +  return state_ == GuardState::kSpoken;
Интересный выбор форм глаголов)
Может ```kDialogFinished``` и ```IsDialogFinished()```? А то все мои идеи с spoke или has spoken звучат стремно.

2021-04-23 22:10 UTC, maxim12321 commented on src/levels/bsu_entrance/guard_behaviour.cpp
> +  } else if (player_dist > kRunRadius
Тут как-то всё совсем смешалось, надо попробовать прибрать.
Во-первых, стоит отделять пустыми строчками какие-то части, связанные логически. Например, первые три строчки, которые вычисляют player_vector и player_dist, отделить от цикла ниже, вычисление значений для охранника отделить от установки состояния и т.д.
Во-вторых, можно вообще вычисление скорости движения охранника в отдельный метод вынести, просто чтобы оно тут не мешало.

2021-04-23 22:10 UTC, maxim12321 commented on src/levels/bsu_entrance/guard_behaviour.cpp
> +              && (state_ == GuardState::kGuarding || state_ == GuardState::kNone)) {
А просто ```state_ != kWandering``` вместо двойной проверки не пойдет?

2021-04-23 22:10 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +  }, contexts.mini_game_context->GetContainer());
Оставлять объявление лямбды в конце строки как-то странно, может так
```
mini_game_ = std::make_shared<GuardMiniGame>(
    [this]() {
      state_ = State::kFinished;
    },
    contexts.mini_game_context->GetContainer()
);
```
Ну или так
```
mini_game_ = std::make_shared<GuardMiniGame>(
    [this]() { state_ = State::kFinished; },
    contexts.mini_game_context->GetContainer()
);
```
Как думаете?

2021-04-23 22:10 UTC, maxim12321 commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +        ProjectPlayerPos(world, contexts));
Не ну, тут точно на отдельную строчку не надо переносить)
Вообще, такого довольно много в коде, вроде же у вас лимит ширины 100 символов. Много где можно убрать лишние переносы строк.
Посмотрите, пожалуйста.

2021-04-26 18:20 UTC, dranikpg commented on src/levels/bsu_entrance/guard_behaviour.cpp
> +              && (state_ == GuardState::kGuarding || state_ == GuardState::kNone)) {
Нет, еще `kDialogFinished` исключить надо

2021-04-26 18:21 UTC, dranikpg commented on src/levels/bsu_entrance/bsu_entrance_level.cpp
> +  }, contexts.mini_game_context->GetContainer());
Поддерживаю второй вариант

2021-04-26 18:58 UTC, dranikpg commented on src/systems/dialog_system.cpp
> +  }
Забыл убрать

2021-04-27 00:59 UTC, maxim12321 approved these changes

2021-04-27 04:19 UTC, SubaruFallout approved these changes

2021-04-27 16:03 UTC, merged