Sprint 4 secret mini game
dranikpg/bsu-game pull request #17
Opened 2021-05-19 19:52 UTC by NB6361

2021-05-19 20:10 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +SecretMiniGame::PudgeState SecretMiniGame::pudge_state = PudgeState::kWaiting;
Названия точно менять не будем?

2021-05-19 20:11 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +SecretMiniGame::SecretMiniGame(SecretMiniGame::Callback callback,
Может компактнее разместить поля?

2021-05-19 20:12 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +              std::hypotf(SecretMiniGame::Drawer::click_pos.x() - for_updating_.x(),
Может вынести вычисление std::hypotf отдельно? Тем более оно второй раз используется

2021-05-19 20:13 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +                            (coordinate.first.x() - QPixmap(":/target.png").width() / 18.),
Создание пиксмапы лучше вынести из функции

2021-05-19 20:14 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +        hook_coordinates -= 7 * curr_vector;
Может некоторые константы вынесем в статичные поля?

2021-05-19 20:14 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +    if (timer_ > 200) {
И эту тоже

2021-05-19 20:14 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +  painter.drawPixmap(hook_coordinates.x() - ok_.width() / 2. + hook.width() / 2.,
>> сдвиг

2021-05-19 20:16 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +                  QPixmap(":/chel_with_labs.png").width() / 8.,
В этом месте точно не стоит создавать пиксмапу

2021-05-19 20:16 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +                  QPixmap(":/chel_with_labs.png").width() / 8.,
Может создание пискмапы вынести из аргументов?

2021-05-19 20:17 UTC, dranikpg commented on src/levels/bsu_entrance/secret_mini_game.cpp
> +  hook_coordinates = for_updating_ - QPointF(QPixmap(":/laba.png").width() / 2.,
0 не влез?

2021-05-19 20:17 UTC, dranikpg requested changes
Несколько придирок к кодстайлу

2021-05-20 18:23 UTC, SubaruFallout requested changes

2021-05-20 18:23 UTC, SubaruFallout commented on src/levels/bsu_entrance/secret_mini_game.h
> +    ecs::Entity* target = nullptr;
Последний боец потерял нижнее подчеркивание

2021-05-21 08:17 UTC, dranikpg approved these changes

2021-05-21 08:44 UTC, dranikpg approved these changes

2021-05-21 08:46 UTC, SubaruFallout approved these changes

2021-05-21 08:47 UTC, maxim12321 approved these changes

2021-05-21 08:47 UTC, merged