Sprint 1
dranikpg/bsu-game pull request #3
Opened 2021-02-26 15:59 UTC by dranikpg

Содержит компоненты для позиции, спрайта и камера, систему для отрисовки спрайтов, контекст для передачи QPainter и прототип для запуска проекта.

2021-02-26 17:25 UTC, NB6361 commented on src/components/position_component.cpp
> +}
лучше фигурную скобку оставить на первой строке

2021-02-26 17:25 UTC, NB6361 commented on src/components/sprite_component.cpp
> +    : pixmap(pixmap), area(pixmap.rect()), size(pixmap.rect()), offset(0, 0), layer(layer) {
здесь же строка выходит за границы

2021-02-26 17:25 UTC, NB6361 commented on src/components/position_component.cpp
>  PositionComponent::PositionComponent(const QPoint& pos) : pos(pos) {
опять же хочется перенести фигурную скобку в эту строку, как в следующем конструкторе

2021-02-26 17:25 UTC, NB6361 commented on src/resources/animation.cpp
> +    : pixmap_(pixmap), frames_(std::move(frames)), frame_lengths_(std::move(frame_lengths)) {}
опять в строку не влазит(

2021-02-26 17:25 UTC, NB6361 commented on src/components/sprite_component.h
> +  void updateGraphics(const QPixmap& pixmap, const QRect& area);
мы же вроде не пишем методы в компонентах, почему бы не сделать системку?

2021-02-27 13:04 UTC, maxim12321 requested changes

2021-02-27 13:04 UTC, maxim12321 commented on src/components/position_component.h
> +  QPoint pos;
Давайте по максимуму откажемся от сокращений, вроде же ```position``` не сильно длиннее)

2021-02-27 13:04 UTC, maxim12321 commented on src/components/sprite_component.h
> +  SpriteLayer layer;
Лучше разделять конструкторы, методы и поля хотя бы пустыми строками, что-то вроде
```
SpriteComponent(...);
SpriteComponent(...);

void UpdateGraphics(...);

QPixmap ...
```
Так будет проще читать заголовочный файл

2021-02-27 13:04 UTC, maxim12321 commented on src/components/sprite_component.h
> +  QRect bounds;
Можно как-то более понятно назвать эти поля? А то без чтения кода в RenderingSystem не особо понятно, что есть что)
Может что-то вроде ```sourse_bounds```, ```target_bounds```.
И надо ли тут оба этих поля, разве будет ```area != bounds```?

2021-02-27 13:04 UTC, maxim12321 commented on src/components/sprite_component.cpp
> +SpriteComponent::SpriteComponent(const QPixmap& pixmap,
Ну и тут пустую строчку, пожалуйста :)

2021-02-27 13:04 UTC, maxim12321 commented on src/context/painter_context.h
> +  QPainter& Acquire();
Может просто ```GetPainter```, ```SetPainter```? Методы же именно это делают
И снова, пустую строку после методов, перед private: хотелось бы

2021-02-27 13:04 UTC, maxim12321 commented on src/prototype/prototype_widget.cpp
> +  */
Для чего оставлять закомментированный пример использования этого всего? Он же даже локально не будет работать правильно, как минимум из-за отсутствия картинки.
Давайте либо делать рабочие примеры, либо не делать их вообще

2021-02-27 13:04 UTC, maxim12321 commented on src/prototype/prototype_widget.h
> +  context::PainterContext painter_context_{};
Во-первых, опять пустой строчки не хватает)
Во-вторых, может все же инициализировать поля через конструктор? А то как-то не по-пацански смотрится

2021-02-27 13:04 UTC, maxim12321 commented on src/prototype/prototype_widget.cpp
> +#include "../components/camera_component.h"
Все эти инклюды должны быть в заголовочном файле ```prototype_widget.h```

2021-02-27 13:04 UTC, maxim12321 commented on src/resources/animation.cpp
> +#include <utility>
Снова инклюд в хедер надо вынести

2021-02-27 13:04 UTC, maxim12321 commented on src/resources/animation.h
> +  size_t GetFrameCount();
Для метода лучше отдельный раздел private:, причем выше, чем поля (чтобы везде одинакового стиля придерживаться).
Ну и про пустые строчки перед разделами private не забываем-с

2021-02-27 13:04 UTC, maxim12321 commented on src/systems/rendering_system.cpp
> +#include <QPainter>
:confused:

2021-02-27 13:04 UTC, maxim12321 commented on src/systems/rendering_system.h
> + private:
Тут звездочка не туда прилипла))
Ну и да-да, пустая строчка снова

2021-02-27 13:04 UTC, maxim12321 commented on src/systems/rendering_system.cpp
> +      bounds.translate(-bounds.width() / 2, -bounds.height() / 2);
Видимо, ```position``` это позиция центра прямоугольника. Тогда можно писать вот так
```
QRect bounds = sprite.bounds;
bounds.moveCenter(position.pos);
```

2021-02-27 13:29 UTC, maxim12321 approved these changes

2021-02-27 13:31 UTC, NB6361 approved these changes

2021-02-27 13:33 UTC, merged