Sprint 1 collision
dranikpg/bsu-game pull request #4
Opened 2021-03-05 20:48 UTC by NB6361

Added movement and collisions. Now you can move pressing wasd

2021-03-06 12:49 UTC, dranikpg commented on CMakeLists.txt
> +        src/resources/animation.cpp src/components/impulse_component.cpp src/systems/movement_system.cpp src/components/bounds_component.cpp  src/context/input_context.cpp src/systems/input_movement_
Стоит разнести все по отдельным строчкам и добавить movement_system.cpp

2021-03-06 12:51 UTC, dranikpg commented on src/context/input_context.h
> +  void SetKeys(Qt::Key key);
Лучше, наверное, назвать метод `AddKey` или `KeyPressed`

2021-03-06 12:53 UTC, dranikpg commented on src/main.cpp
> -  prototype.resize(300, 100);
😑

2021-03-06 12:55 UTC, dranikpg commented on src/systems/input_movement_system.cpp
> +  for (auto& entity : world->ScanEntities<InputMovementComponent, ImpulseComponent>()) {
вместо `ScanEntities` можно использовать просто `Scan`

2021-03-06 12:57 UTC, dranikpg commented on src/systems/input_movement_system.cpp
> +      }
Хотелось бы вынести скорость, для начала, в некоторую приватную константу, а также проверять не больше ли `shfit` чем допустимая скорость

2021-03-06 22:40 UTC, maxim12321 requested changes

2021-03-06 22:40 UTC, maxim12321 commented on src/context/input_context.h
> +  std::set<constants::Keys> seq_of_keys_{};
Так как клавиш, нужных в игре, ограниченное количество, то можно просто завести ```vector<bool>```, нажата клавиша в данный момент или нет.
Индекс клавиши в этом векторе можно получать, делая ```static_cast<int>(Key)```.
Если сделать так, то вместо ```switch``` в ```AddKey``` останется примерно одна строчка)
Более того, такой вариант более удобен при добавлении новых клавиш в будущем, а они обязательно добавятся.

2021-03-06 22:40 UTC, maxim12321 commented on src/context/input_context.h
> +  std::set<constants::Keys> seq_of_keys_{};
И еще, так как этому вектору необходимо задать размер, то можно добавить в ```constants::Keys``` еще один элемент, что-то вроде ```kAnyKey```, по аналогии с ```_LAST``` в ```SpriteLayer```, который **всегда будет последним** в этом енаме.
Тогда количество элементов в енаме можно будет вычислить с помощью ```static_cast<int>(Keys::kAnyKey)```.

2021-03-06 22:40 UTC, maxim12321 commented on src/systems/input_movement_system.cpp
> +    for (auto key : keys) {
Если сделать внутри ```InputContext``` вектор вместо сета, то можно вместо метода ```GetKeys()``` сделать что-то вроде ```IsKeyDown(Key)``` и просто проверить 4 клавиши.
Либо, второй вариант, можно завести что-то вроде списка пар <Key, QPoint>, который будет хранить для клавиши вектор перемещения, который она прибавляет (векторы можно и единичными сделать), тогда вообще весь код тут превратиться в один for-loop по этому списку пар.

2021-03-06 22:40 UTC, maxim12321 commented on src/systems/movement_system.cpp
> +    impulse.shift = QPoint(0, 0);
Проверку стоит делать по разным осям по отдельности, сначала прибавлять только одну координату, потом только другую.
Кроме того, что это правильнее, еще и сильно упрощается проверка на прохождение через препятствие. Тут уже нет необходимости строить линии через соответствующие точки прямоугольника.
Пусть сейчас мы хотим проверить движение вправо:
Можно, например, сделать общий прямоугольник, для которого левая сторона - текущая левая граница объекта, а правая - правая граница объекта после перемещения. Тогда для проверки пересечения достаточно проверить, что этот прямоугольник пересекается с прямоугольником препятствия (один метод ```intersects```).

2021-03-06 22:40 UTC, maxim12321 commented on src/systems/movement_system.cpp
> +    impulse.shift = QPoint(0, 0);
Только надо сделать это аккуратно, чтобы не превратить в разбор случаев :)
Например, просто выбирать минимум и максимум из точек, ну или что-то такое

2021-03-06 22:40 UTC, maxim12321 commented on src/systems/movement_system.cpp
> +    }
Если же не получится сделать что-то аккуратное там, то можно будет просто вынести такую проверку в отдельный метод, что-то вроде
```bool Intersects(QRectF current, QRectF target, QRectF obstacle);```
Для того, чтобы не писать всё в одной куче.

2021-03-10 13:09 UTC, dranikpg approved these changes

2021-03-10 15:35 UTC, maxim12321 requested changes

2021-03-10 15:35 UTC, maxim12321 commented on src/systems/movement_system.cpp
> +bool MovementSystem::IsIntersects(World* world, Entity* entity,
Давайте только не ```IsIntersects```, а просто ```Intersects```, не будем ломать английский)

2021-03-10 15:35 UTC, maxim12321 commented on src/systems/movement_system.cpp
>    for (auto& another_entity : world->ScanEntities<PositionComponent, ColliderComponent,
Может все же передать только один прямоугольник, что-то вроде ```const QRect& target```, а внутри IsColliding... просто вызвать два раза. А то так стремно как-то, делать if внутри функции, а не снаружи, кажется функцию Intersects это не должно волновать.

2021-03-10 15:35 UTC, maxim12321 commented on src/systems/movement_system.cpp
> +                                       entity_rect.center().y()));
А для этого можно делать
```QRect destination_rect = entity_rect.translated(x_shift, 0);```

2021-03-10 15:35 UTC, maxim12321 commented on src/systems/movement_system.cpp
> +                              entity_rect.center().y() + y_shift));
Ну и тут аналогично, можно в одну строчку

2021-03-10 18:00 UTC, maxim12321 approved these changes

2021-03-10 18:03 UTC, merged