Sprint 1 animation (part 1)
dranikpg/bsu-game pull request #5
Opened 2021-03-06 14:23 UTC by shauneu

Добавлены AnimationSystem и AnimationComponent

2021-03-06 22:57 UTC, maxim12321 requested changes

2021-03-06 22:57 UTC, maxim12321 commented on src/components/sprite_component.cpp
> +}
Закрывающую фигурную скобочку на предыдущую строчку, пожалуйста :)

2021-03-06 22:57 UTC, maxim12321 commented on src/systems/animation_system.cpp
> +                       animation.animation_resource_->GetFrame(animation.frame_index));
В SpriteComponent хранится QPixmap, а в этом методе он, видимо, передается по ссылке, а затем копируется. Кажется, что это не очень хорошо, хотя пока что не сильно значительно.
Можно сделать одно из двух:
* Просто переместить этот SetGraphics внутрь ифов, то есть, устанавливать графику только когда меняется кадр (так себе решение, не сильно лучше)
* Хранить (в SpriteComponent) и передавать указатели на эти QPixmap, которые создаваться будут в Animation. То есть, в Animation делать геттеры не QPixmap, а указателей на него, чтобы картинки не копировать.

2021-03-06 22:57 UTC, maxim12321 commented on src/systems/animation_system.h
> +using ecs::World;
Может тут тоже не надо using делать, а то в других местах вроде нет его. Кажется он не сильно нужен

2021-03-07 15:56 UTC, dranikpg commented on src/systems/animation_system.cpp
> +                       animation.animation_resource_->GetFrame(animation.frame_index));
Копирование тут не происходит
https://doc.qt.io/qt-5/implicit-sharing.html

2021-03-09 17:51 UTC, dranikpg approved these changes

2021-03-10 12:56 UTC, merged