Sprint 1 animation (part 2)
dranikpg/bsu-game pull request #7
Opened 2021-03-17 05:54 UTC by shauneu

Добавлена возможность синхронизировать анимации и действия.

2021-03-17 14:42 UTC, SubaruFallout requested changes

2021-03-17 14:42 UTC, SubaruFallout commented on CMakeLists.txt
> +        src/constants/animation_type.h)
.h файлы добавлять не нужно

2021-03-17 14:42 UTC, SubaruFallout commented on src/systems/animation_system.cpp
> +    if ((animation.frame_index == (animation.total_frames-1))
Вроде должны быть пробелы между минусом

2021-03-17 19:36 UTC, maxim12321 requested changes

2021-03-17 19:36 UTC, maxim12321 commented on src/constants/animation_type.h
> +  kShiftRightUpCorner,
А что означает префикс Shift во всех названиях? Видимо это просто взято из названия поля в ImpulseComponent. Просто shift это "сдвиг", а в контексте типа анимации как-то не очень понятно.
Может его убрать, ну или заменить чем-то более подходящим по смыслу?
То же самое и со словом Corner, можно использовать просто Up, UpLeft, например
И AnimationType тоже довольно абстрактная фраза, может AnimationDirection или что-то такое
В общем, надо подумать над именами всего этого

2021-03-17 19:36 UTC, maxim12321 commented on src/systems/animation_sync_system.cpp
> +  ShiftHandler(world);
Может лучше сделать один цикл, который будет сразу определять нужную следующую анимацию и ставить ее? А в отдельные методы вынести только логику по выбору анимации в зависимости от shift или рандомно.
Так и более явным будет порядок выполнения всего этого, заодно.
То есть, предлагаю сделать что-то такое:
```
for (auto[sync, animation, impulse] : ...) {
  if (impulse.shift.isNull()) {
    current_animation = GetRandomDefaultAnimation(animation);
    // Ставим AnimationType на Default, еще что-то тут...
  } else {
    AnimationType deduced_type = GetAnimationType(impulse.shift);
    // Выставляем нужный тип и переключаем анимацию...
  }
}
```

2021-03-20 17:33 UTC, shauneu commented on src/systems/animation_sync_system.cpp
> +  ShiftHandler(world);
Возможно потом исправлю. На функциональность это не влияет.

2021-03-20 17:37 UTC, dranikpg approved these changes

2021-03-20 17:51 UTC, NB6361 approved these changes

2021-03-20 17:51 UTC, NB6361 commented on src/constants/animation_type.h
> +#endif  // SRC_CONSTANTS_ANIMATION_TYPE_H_
у нас есть почти такое же перечисление(добавить дефолт), там можно поменять название и использовать его, а не создавать новое

2021-03-20 17:51 UTC, NB6361 commented on src/systems/movement_animation_sync_system.cpp
> +    int yshift = impulse.shift.y();
назови нормально, x_shift, y_shift

2021-03-20 18:02 UTC, shauneu commented on src/constants/animation_type.h
> +#endif  // SRC_CONSTANTS_ANIMATION_TYPE_H_
Суть в том что в это перечисление потом добавятся другие типы анимаций.

2021-03-20 18:02 UTC, shauneu commented on src/systems/movement_animation_sync_system.cpp
> +    int yshift = impulse.shift.y();
)

2021-03-20 18:29 UTC, SubaruFallout approved these changes

2021-03-22 16:12 UTC, maxim12321 approved these changes

2021-03-26 19:14 UTC, merged