Sprint 2 path follow
dranikpg/bsu-game pull request #9
Opened 2021-04-03 12:44 UTC by shauneu

Реализована возможность объекта ходить по заданному пути.

2021-04-03 12:57 UTC, dranikpg commented on src/systems/path_follow_system.cpp
> +        case PathFollowState::kMoving: {
Зачем отдельный блок с { ?

2021-04-03 13:09 UTC, dranikpg commented on src/components/path_follow_component.h
> +  std::shared_ptr<resource::Path> path;
Если этот путь будет изменен - то его стоит принимать по значению

2021-04-03 13:49 UTC, maxim12321 requested changes

2021-04-03 13:49 UTC, maxim12321 commented on src/components/path_follow_component.h
> +  qreal speed;
Из документации про qreal: ```Typedef for double unless Qt is configured with the -qreal float option```.
Давайте просто double или float ставить, а не вот это всё

2021-04-03 13:49 UTC, maxim12321 commented on src/components/path_follow_component.h
> +  int waypoint_length;
Может лучше ```current_waypoint```, ```wait_timer``` и ```wait_duration```, например?

2021-04-03 13:49 UTC, maxim12321 commented on src/systems/path_follow_system.cpp
> +      switch (pf_component.state) {
А будет ли приятнее, если немного переставить и получить что-то такое:
```
if (pf_component.state == PathFollowState::kWaiting) { ... }
else if (pf_component.state == PathFollowState::kMoving) { ... }
else if (pf_component.state == PathFollowState::kFinished) {
  return; 
}

if (pf_component.state == PathFollowState::kResolvingMoving) {
  pf_component.state = PathFollowState::kWaiting;
  WaitOneTerm(&pf_component);
}

if (pf_component.state == PathFollowState::kResolvingWaiting) { ... }
```
Вместо всех этих циклов, свитчей, кейсов, брейков. Кажется работать так же должно.

2021-04-03 13:49 UTC, maxim12321 commented on src/systems/path_follow_system.cpp
> +        new_waypoint_idx = current_waypoint_idx+1;
Пробелы вокруг плюса куда-то пропали 😕

2021-04-03 13:49 UTC, maxim12321 commented on src/systems/path_follow_system.cpp
> +  }
Можно ведь просто 
```
pf_component->waypoint_time++;
if (pf_component->waypoint_time > pf_component->waypoint_length) {
  pf_component->state = PathFollowState::kResolvingWaiting;
}
```

2021-04-04 07:07 UTC, shauneu commented on src/systems/path_follow_system.cpp
> +      switch (pf_component.state) {
Не согласен. Цикл явно дает понять что обработка идет пока не получится одно из валидных состояний. Мне кажется его логика более прозрачна.

2021-04-04 07:13 UTC, shauneu commented on src/systems/path_follow_system.cpp
> +        case PathFollowState::kMoving: {
https://stackoverflow.com/questions/61708267/jump-bypasses-variable-initialization-in-switch-statement

2021-04-04 11:05 UTC, maxim12321 commented on src/systems/path_follow_system.cpp
> +        case PathFollowState::kMoving: {
Так давайте все содержимое case будем оборачивать в фигурные скобки, включая break. И так для однообразия во всех кейсах

2021-04-05 18:09 UTC, dranikpg approved these changes

2021-04-05 18:44 UTC, maxim12321 approved these changes

2021-04-07 06:55 UTC, merged